# Generated by Django 3.0.1 on 2019-12-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='urlshort',
            field=models.CharField(max_length=100),
        ),
    ]
