# Generated by Django 3.0.1 on 2019-12-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0002_auto_20191224_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='urlshort',
            field=models.CharField(max_length=500),
        ),
    ]
