# Generated by Django 3.0.1 on 2019-12-25 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0003_auto_20191225_2105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Shortner',
        ),
    ]
