# Generated by Django 3.0.1 on 2019-12-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0004_auto_20191225_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortner',
            name='urlshort',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
